//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppTest3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testbd2Entities : DbContext
    {
        public testbd2Entities()
            : base("name=testbd2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ImageTable> ImageTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Вещи> Вещи { get; set; }
        public virtual DbSet<Вещи_Инвентарь> Вещи_Инвентарь { get; set; }
        public virtual DbSet<Гильдия> Гильдия { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Достижения> Достижения { get; set; }
        public virtual DbSet<Инвентарь> Инвентарь { get; set; }
        public virtual DbSet<Класс> Класс { get; set; }
        public virtual DbSet<Персонаж> Персонаж { get; set; }
        public virtual DbSet<Персонаж_Достижение> Персонаж_Достижение { get; set; }
        public virtual DbSet<Рынок> Рынок { get; set; }
        public virtual DbSet<Фракция> Фракция { get; set; }
    }
}
